kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: workload-controller-manager-role-binding
  namespace: kube-system
subjects:
- kind: User
  name: system:workload-controller-manager
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: workload-controller-manager-role
  apiGroup: ""
