/*
Copyright The Kubernetes Authors.
Copyright 2020 Authors of Arktos - file modified.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"time"

	"k8s.io/apiextensions-apiserver/pkg/client/clientset/internalclientset/scheme"
	rand "k8s.io/apimachinery/pkg/util/rand"
	rest "k8s.io/client-go/rest"
)

type ApiextensionsInterface interface {
	RESTClient() rest.Interface
	RESTClients() []rest.Interface
	CustomResourceDefinitionsGetter
}

// ApiextensionsClient is used to interact with features provided by the apiextensions.k8s.io group.
type ApiextensionsClient struct {
	restClients []rest.Interface
}

func (c *ApiextensionsClient) CustomResourceDefinitions() CustomResourceDefinitionInterface {
	return newCustomResourceDefinitions(c)
}

// NewForConfig creates a new ApiextensionsClient for the given config.
func NewForConfig(c *rest.Config) (*ApiextensionsClient, error) {
	configs := rest.CopyConfigs(c)
	if err := setConfigDefaults(configs); err != nil {
		return nil, err
	}

	clients := make([]rest.Interface, len(configs.GetAllConfigs()))
	for i, config := range configs.GetAllConfigs() {
		client, err := rest.RESTClientFor(config)
		if err != nil {
			return nil, err
		}
		clients[i] = client
	}

	return &ApiextensionsClient{clients}, nil
}

// NewForConfigOrDie creates a new ApiextensionsClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ApiextensionsClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ApiextensionsClient for the given RESTClient.
func New(c rest.Interface) *ApiextensionsClient {
	clients := []rest.Interface{c}
	return &ApiextensionsClient{clients}
}

func setConfigDefaults(configs *rest.Config) error {
	for _, config := range configs.GetAllConfigs() {
		config.APIPath = "/apis"
		if config.UserAgent == "" {
			config.UserAgent = rest.DefaultKubernetesUserAgent()
		}
		if config.GroupVersion == nil || config.GroupVersion.Group != scheme.Scheme.PrioritizedVersionsForGroup("apiextensions.k8s.io")[0].Group {
			gv := scheme.Scheme.PrioritizedVersionsForGroup("apiextensions.k8s.io")[0]
			config.GroupVersion = &gv
		}
		config.NegotiatedSerializer = scheme.Codecs

		if config.QPS == 0 {
			config.QPS = 5
		}
		if config.Burst == 0 {
			config.Burst = 10
		}
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ApiextensionsClient) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}

	max := len(c.restClients)
	if max == 0 {
		return nil
	}
	if max == 1 {
		return c.restClients[0]
	}

	rand.Seed(time.Now().UnixNano())
	ran := rand.IntnRange(0, max-1)
	return c.restClients[ran]
}

// RESTClients returns all RESTClient that are used to communicate
// with all API servers by this client implementation.
func (c *ApiextensionsClient) RESTClients() []rest.Interface {
	if c == nil {
		return nil
	}

	return c.restClients
}
