/*
Copyright 2020 Authors of Arktos.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeActions implements ActionInterface
type FakeActions struct {
	Fake *FakeCoreV1
	ns   string
	te   string
}

var actionsResource = schema.GroupVersionResource{Group: "", Version: "v1", Resource: "actions"}

var actionsKind = schema.GroupVersionKind{Group: "", Version: "v1", Kind: "Action"}

// Get takes name of the action, and returns the corresponding action object, and an error if there is any.
func (c *FakeActions) Get(name string, options v1.GetOptions) (result *corev1.Action, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithMultiTenancy(actionsResource, c.ns, name, c.te), &corev1.Action{})

	if obj == nil {
		return nil, err
	}

	return obj.(*corev1.Action), err
}

// List takes label and field selectors, and returns the list of Actions that match those selectors.
func (c *FakeActions) List(opts v1.ListOptions) (result *corev1.ActionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithMultiTenancy(actionsResource, actionsKind, c.ns, opts, c.te), &corev1.ActionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &corev1.ActionList{ListMeta: obj.(*corev1.ActionList).ListMeta}
	for _, item := range obj.(*corev1.ActionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.AggregatedWatchInterface that watches the requested actions.
func (c *FakeActions) Watch(opts v1.ListOptions) watch.AggregatedWatchInterface {
	aggWatch := watch.NewAggregatedWatcher()
	watcher, err := c.Fake.
		InvokesWatch(testing.NewWatchActionWithMultiTenancy(actionsResource, c.ns, opts, c.te))

	aggWatch.AddWatchInterface(watcher, err)
	return aggWatch
}

// Create takes the representation of a action and creates it.  Returns the server's representation of the action, and an error, if there is any.
func (c *FakeActions) Create(action *corev1.Action) (result *corev1.Action, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithMultiTenancy(actionsResource, c.ns, action, c.te), &corev1.Action{})

	if obj == nil {
		return nil, err
	}

	return obj.(*corev1.Action), err
}

// Update takes the representation of a action and updates it. Returns the server's representation of the action, and an error, if there is any.
func (c *FakeActions) Update(action *corev1.Action) (result *corev1.Action, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithMultiTenancy(actionsResource, c.ns, action, c.te), &corev1.Action{})

	if obj == nil {
		return nil, err
	}

	return obj.(*corev1.Action), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeActions) UpdateStatus(action *corev1.Action) (*corev1.Action, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithMultiTenancy(actionsResource, "status", c.ns, action, c.te), &corev1.Action{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.Action), err
}

// Delete takes name of the action and deletes it. Returns an error if one occurs.
func (c *FakeActions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithMultiTenancy(actionsResource, c.ns, name, c.te), &corev1.Action{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeActions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithMultiTenancy(actionsResource, c.ns, listOptions, c.te)

	_, err := c.Fake.Invokes(action, &corev1.ActionList{})
	return err
}

// Patch applies the patch and returns the patched action.
func (c *FakeActions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *corev1.Action, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithMultiTenancy(actionsResource, c.te, c.ns, name, pt, data, subresources...), &corev1.Action{})

	if obj == nil {
		return nil, err
	}

	return obj.(*corev1.Action), err
}
