/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	cloudgatewayv1 "k8s.io/kubernetes/pkg/apis/cloudgateway/v1"
	versioned "k8s.io/kubernetes/pkg/client/clientset/versioned"
	internalinterfaces "k8s.io/kubernetes/pkg/client/informers/externalversions/internalinterfaces"
	v1 "k8s.io/kubernetes/pkg/client/listers/cloudgateway/v1"
)

// ServiceExposeInformer provides access to a shared informer and lister for
// ServiceExposes.
type ServiceExposeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ServiceExposeLister
}

type serviceExposeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
	tenant           string
}

// NewServiceExposeInformer constructs a new informer for ServiceExpose type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewServiceExposeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredServiceExposeInformer(client, namespace, resyncPeriod, indexers, nil)
}

func NewServiceExposeInformerWithMultiTenancy(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tenant string) cache.SharedIndexInformer {
	return NewFilteredServiceExposeInformerWithMultiTenancy(client, namespace, resyncPeriod, indexers, nil, tenant)
}

// NewFilteredServiceExposeInformer constructs a new informer for ServiceExpose type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredServiceExposeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewFilteredServiceExposeInformerWithMultiTenancy(client, namespace, resyncPeriod, indexers, tweakListOptions, "system")
}

func NewFilteredServiceExposeInformerWithMultiTenancy(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc, tenant string) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudgatewayV1().ServiceExposesWithMultiTenancy(namespace, tenant).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) watch.AggregatedWatchInterface {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudgatewayV1().ServiceExposesWithMultiTenancy(namespace, tenant).Watch(options)
			},
		},
		&cloudgatewayv1.ServiceExpose{},
		resyncPeriod,
		indexers,
	)
}

func (f *serviceExposeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredServiceExposeInformerWithMultiTenancy(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions, f.tenant)
}

func (f *serviceExposeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cloudgatewayv1.ServiceExpose{}, f.defaultInformer)
}

func (f *serviceExposeInformer) Lister() v1.ServiceExposeLister {
	return v1.NewServiceExposeLister(f.Informer().GetIndexer())
}
