{{$WINDOWS_NODE_NAME := DefaultParam .WINDOWS_NODE_NAME ""}}

apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: windows-scrape-configs
stringData:
  windows-scrape-configs.yaml: |-
    - job_name: "monitoring/windows_static"
      scrape_interval: {{DefaultParam .CL2_WINDOWS_SCRAPE_INTERVAL "1m"}}
      scrape_timeout: {{DefaultParam .CL2_WINDOWS_SCRAPE_TIMEOUT "10s"}}
      static_configs:
      - targets: ["{{$WINDOWS_NODE_NAME}}:5000"]
