apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    size: {{.ILBSizeLabel}}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    name: {{.DeploymentBaseName}}-{{.Index}}
  ports:
  - port: 8080
    targetPort: 80
