apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: probes
  name: dns
spec:
  endpoints:
    - interval: 30s
      port: metrics
  namespaceSelector:
    matchNames:
      - probes
  selector:
    matchLabels:
      probe: dns
