/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: builtins.proto

package mizar

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CodeType int32

const (
	CodeType_OK         CodeType = 0
	CodeType_TEMP_ERROR CodeType = 1
	CodeType_PERM_ERROR CodeType = 2
)

var CodeType_name = map[int32]string{
	0: "OK",
	1: "TEMP_ERROR",
	2: "PERM_ERROR",
}

var CodeType_value = map[string]int32{
	"OK":         0,
	"TEMP_ERROR": 1,
	"PERM_ERROR": 2,
}

func (x CodeType) String() string {
	return proto.EnumName(CodeType_name, int32(x))
}

func (CodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_54ab063ef2b175be, []int{0}
}

type BuiltinsNodeMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuiltinsNodeMessage) Reset()         { *m = BuiltinsNodeMessage{} }
func (m *BuiltinsNodeMessage) String() string { return proto.CompactTextString(m) }
func (*BuiltinsNodeMessage) ProtoMessage()    {}
func (*BuiltinsNodeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ab063ef2b175be, []int{0}
}
func (m *BuiltinsNodeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuiltinsNodeMessage.Unmarshal(m, b)
}
func (m *BuiltinsNodeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuiltinsNodeMessage.Marshal(b, m, deterministic)
}
func (m *BuiltinsNodeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuiltinsNodeMessage.Merge(m, src)
}
func (m *BuiltinsNodeMessage) XXX_Size() int {
	return xxx_messageInfo_BuiltinsNodeMessage.Size(m)
}
func (m *BuiltinsNodeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BuiltinsNodeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BuiltinsNodeMessage proto.InternalMessageInfo

func (m *BuiltinsNodeMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuiltinsNodeMessage) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type BuiltinsPodMessage struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HostIp               string               `protobuf:"bytes,2,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	Namespace            string               `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Tenant               string               `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Labels               string               `protobuf:"bytes,5,opt,name=labels,proto3" json:"labels,omitempty"`
	ArktosNetwork        string               `protobuf:"bytes,6,opt,name=arktos_network,json=arktosNetwork,proto3" json:"arktos_network,omitempty"`
	Phase                string               `protobuf:"bytes,7,opt,name=phase,proto3" json:"phase,omitempty"`
	Interfaces           []*InterfacesMessage `protobuf:"bytes,8,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Vpc                  string               `protobuf:"bytes,9,opt,name=vpc,proto3" json:"vpc,omitempty"`
	Subnet               string               `protobuf:"bytes,10,opt,name=subnet,proto3" json:"subnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BuiltinsPodMessage) Reset()         { *m = BuiltinsPodMessage{} }
func (m *BuiltinsPodMessage) String() string { return proto.CompactTextString(m) }
func (*BuiltinsPodMessage) ProtoMessage()    {}
func (*BuiltinsPodMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ab063ef2b175be, []int{1}
}
func (m *BuiltinsPodMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuiltinsPodMessage.Unmarshal(m, b)
}
func (m *BuiltinsPodMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuiltinsPodMessage.Marshal(b, m, deterministic)
}
func (m *BuiltinsPodMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuiltinsPodMessage.Merge(m, src)
}
func (m *BuiltinsPodMessage) XXX_Size() int {
	return xxx_messageInfo_BuiltinsPodMessage.Size(m)
}
func (m *BuiltinsPodMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BuiltinsPodMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BuiltinsPodMessage proto.InternalMessageInfo

func (m *BuiltinsPodMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuiltinsPodMessage) GetHostIp() string {
	if m != nil {
		return m.HostIp
	}
	return ""
}

func (m *BuiltinsPodMessage) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *BuiltinsPodMessage) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *BuiltinsPodMessage) GetLabels() string {
	if m != nil {
		return m.Labels
	}
	return ""
}

func (m *BuiltinsPodMessage) GetArktosNetwork() string {
	if m != nil {
		return m.ArktosNetwork
	}
	return ""
}

func (m *BuiltinsPodMessage) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func (m *BuiltinsPodMessage) GetInterfaces() []*InterfacesMessage {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *BuiltinsPodMessage) GetVpc() string {
	if m != nil {
		return m.Vpc
	}
	return ""
}

func (m *BuiltinsPodMessage) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

type BuiltinsServiceMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArktosNetwork        string   `protobuf:"bytes,2,opt,name=arktos_network,json=arktosNetwork,proto3" json:"arktos_network,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Tenant               string   `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Ip                   string   `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuiltinsServiceMessage) Reset()         { *m = BuiltinsServiceMessage{} }
func (m *BuiltinsServiceMessage) String() string { return proto.CompactTextString(m) }
func (*BuiltinsServiceMessage) ProtoMessage()    {}
func (*BuiltinsServiceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ab063ef2b175be, []int{2}
}
func (m *BuiltinsServiceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuiltinsServiceMessage.Unmarshal(m, b)
}
func (m *BuiltinsServiceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuiltinsServiceMessage.Marshal(b, m, deterministic)
}
func (m *BuiltinsServiceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuiltinsServiceMessage.Merge(m, src)
}
func (m *BuiltinsServiceMessage) XXX_Size() int {
	return xxx_messageInfo_BuiltinsServiceMessage.Size(m)
}
func (m *BuiltinsServiceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BuiltinsServiceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BuiltinsServiceMessage proto.InternalMessageInfo

func (m *BuiltinsServiceMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuiltinsServiceMessage) GetArktosNetwork() string {
	if m != nil {
		return m.ArktosNetwork
	}
	return ""
}

func (m *BuiltinsServiceMessage) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *BuiltinsServiceMessage) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *BuiltinsServiceMessage) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type BuiltinsServiceEndpointMessage struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string          `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Tenant               string          `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	BackendIps           []string        `protobuf:"bytes,4,rep,name=backend_ips,json=backendIps,proto3" json:"backend_ips,omitempty"`
	Ports                []*PortsMessage `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	BackendIpsJson       string          `protobuf:"bytes,6,opt,name=backend_ips_json,json=backendIpsJson,proto3" json:"backend_ips_json,omitempty"`
	PortsJson            string          `protobuf:"bytes,7,opt,name=ports_json,json=portsJson,proto3" json:"ports_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BuiltinsServiceEndpointMessage) Reset()         { *m = BuiltinsServiceEndpointMessage{} }
func (m *BuiltinsServiceEndpointMessage) String() string { return proto.CompactTextString(m) }
func (*BuiltinsServiceEndpointMessage) ProtoMessage()    {}
func (*BuiltinsServiceEndpointMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ab063ef2b175be, []int{3}
}
func (m *BuiltinsServiceEndpointMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuiltinsServiceEndpointMessage.Unmarshal(m, b)
}
func (m *BuiltinsServiceEndpointMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuiltinsServiceEndpointMessage.Marshal(b, m, deterministic)
}
func (m *BuiltinsServiceEndpointMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuiltinsServiceEndpointMessage.Merge(m, src)
}
func (m *BuiltinsServiceEndpointMessage) XXX_Size() int {
	return xxx_messageInfo_BuiltinsServiceEndpointMessage.Size(m)
}
func (m *BuiltinsServiceEndpointMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BuiltinsServiceEndpointMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BuiltinsServiceEndpointMessage proto.InternalMessageInfo

func (m *BuiltinsServiceEndpointMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuiltinsServiceEndpointMessage) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *BuiltinsServiceEndpointMessage) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *BuiltinsServiceEndpointMessage) GetBackendIps() []string {
	if m != nil {
		return m.BackendIps
	}
	return nil
}

func (m *BuiltinsServiceEndpointMessage) GetPorts() []*PortsMessage {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *BuiltinsServiceEndpointMessage) GetBackendIpsJson() string {
	if m != nil {
		return m.BackendIpsJson
	}
	return ""
}

func (m *BuiltinsServiceEndpointMessage) GetPortsJson() string {
	if m != nil {
		return m.PortsJson
	}
	return ""
}

type BuiltinsArktosMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vpc                  string   `protobuf:"bytes,2,opt,name=vpc,proto3" json:"vpc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuiltinsArktosMessage) Reset()         { *m = BuiltinsArktosMessage{} }
func (m *BuiltinsArktosMessage) String() string { return proto.CompactTextString(m) }
func (*BuiltinsArktosMessage) ProtoMessage()    {}
func (*BuiltinsArktosMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ab063ef2b175be, []int{4}
}
func (m *BuiltinsArktosMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuiltinsArktosMessage.Unmarshal(m, b)
}
func (m *BuiltinsArktosMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuiltinsArktosMessage.Marshal(b, m, deterministic)
}
func (m *BuiltinsArktosMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuiltinsArktosMessage.Merge(m, src)
}
func (m *BuiltinsArktosMessage) XXX_Size() int {
	return xxx_messageInfo_BuiltinsArktosMessage.Size(m)
}
func (m *BuiltinsArktosMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BuiltinsArktosMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BuiltinsArktosMessage proto.InternalMessageInfo

func (m *BuiltinsArktosMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuiltinsArktosMessage) GetVpc() string {
	if m != nil {
		return m.Vpc
	}
	return ""
}

type BuiltinsNetworkPolicyMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Tenant               string   `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Policy               string   `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuiltinsNetworkPolicyMessage) Reset()         { *m = BuiltinsNetworkPolicyMessage{} }
func (m *BuiltinsNetworkPolicyMessage) String() string { return proto.CompactTextString(m) }
func (*BuiltinsNetworkPolicyMessage) ProtoMessage()    {}
func (*BuiltinsNetworkPolicyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ab063ef2b175be, []int{5}
}
func (m *BuiltinsNetworkPolicyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuiltinsNetworkPolicyMessage.Unmarshal(m, b)
}
func (m *BuiltinsNetworkPolicyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuiltinsNetworkPolicyMessage.Marshal(b, m, deterministic)
}
func (m *BuiltinsNetworkPolicyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuiltinsNetworkPolicyMessage.Merge(m, src)
}
func (m *BuiltinsNetworkPolicyMessage) XXX_Size() int {
	return xxx_messageInfo_BuiltinsNetworkPolicyMessage.Size(m)
}
func (m *BuiltinsNetworkPolicyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BuiltinsNetworkPolicyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BuiltinsNetworkPolicyMessage proto.InternalMessageInfo

func (m *BuiltinsNetworkPolicyMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuiltinsNetworkPolicyMessage) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *BuiltinsNetworkPolicyMessage) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *BuiltinsNetworkPolicyMessage) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

type BuiltinsNamespaceMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Labels               string   `protobuf:"bytes,3,opt,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuiltinsNamespaceMessage) Reset()         { *m = BuiltinsNamespaceMessage{} }
func (m *BuiltinsNamespaceMessage) String() string { return proto.CompactTextString(m) }
func (*BuiltinsNamespaceMessage) ProtoMessage()    {}
func (*BuiltinsNamespaceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ab063ef2b175be, []int{6}
}
func (m *BuiltinsNamespaceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuiltinsNamespaceMessage.Unmarshal(m, b)
}
func (m *BuiltinsNamespaceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuiltinsNamespaceMessage.Marshal(b, m, deterministic)
}
func (m *BuiltinsNamespaceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuiltinsNamespaceMessage.Merge(m, src)
}
func (m *BuiltinsNamespaceMessage) XXX_Size() int {
	return xxx_messageInfo_BuiltinsNamespaceMessage.Size(m)
}
func (m *BuiltinsNamespaceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BuiltinsNamespaceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BuiltinsNamespaceMessage proto.InternalMessageInfo

func (m *BuiltinsNamespaceMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuiltinsNamespaceMessage) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *BuiltinsNamespaceMessage) GetLabels() string {
	if m != nil {
		return m.Labels
	}
	return ""
}

type PortsMessage struct {
	FrontendPort         string   `protobuf:"bytes,1,opt,name=frontend_port,json=frontendPort,proto3" json:"frontend_port,omitempty"`
	BackendPort          string   `protobuf:"bytes,2,opt,name=backend_port,json=backendPort,proto3" json:"backend_port,omitempty"`
	Protocol             string   `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortsMessage) Reset()         { *m = PortsMessage{} }
func (m *PortsMessage) String() string { return proto.CompactTextString(m) }
func (*PortsMessage) ProtoMessage()    {}
func (*PortsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ab063ef2b175be, []int{7}
}
func (m *PortsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortsMessage.Unmarshal(m, b)
}
func (m *PortsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortsMessage.Marshal(b, m, deterministic)
}
func (m *PortsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortsMessage.Merge(m, src)
}
func (m *PortsMessage) XXX_Size() int {
	return xxx_messageInfo_PortsMessage.Size(m)
}
func (m *PortsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PortsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PortsMessage proto.InternalMessageInfo

func (m *PortsMessage) GetFrontendPort() string {
	if m != nil {
		return m.FrontendPort
	}
	return ""
}

func (m *PortsMessage) GetBackendPort() string {
	if m != nil {
		return m.BackendPort
	}
	return ""
}

func (m *PortsMessage) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type InterfacesMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Subnet               string   `protobuf:"bytes,3,opt,name=subnet,proto3" json:"subnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfacesMessage) Reset()         { *m = InterfacesMessage{} }
func (m *InterfacesMessage) String() string { return proto.CompactTextString(m) }
func (*InterfacesMessage) ProtoMessage()    {}
func (*InterfacesMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ab063ef2b175be, []int{8}
}
func (m *InterfacesMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfacesMessage.Unmarshal(m, b)
}
func (m *InterfacesMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfacesMessage.Marshal(b, m, deterministic)
}
func (m *InterfacesMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfacesMessage.Merge(m, src)
}
func (m *InterfacesMessage) XXX_Size() int {
	return xxx_messageInfo_InterfacesMessage.Size(m)
}
func (m *InterfacesMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfacesMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InterfacesMessage proto.InternalMessageInfo

func (m *InterfacesMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InterfacesMessage) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *InterfacesMessage) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

type ReturnCode struct {
	Code                 CodeType `protobuf:"varint,1,opt,name=code,proto3,enum=mizar.CodeType" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnCode) Reset()         { *m = ReturnCode{} }
func (m *ReturnCode) String() string { return proto.CompactTextString(m) }
func (*ReturnCode) ProtoMessage()    {}
func (*ReturnCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ab063ef2b175be, []int{9}
}
func (m *ReturnCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnCode.Unmarshal(m, b)
}
func (m *ReturnCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnCode.Marshal(b, m, deterministic)
}
func (m *ReturnCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnCode.Merge(m, src)
}
func (m *ReturnCode) XXX_Size() int {
	return xxx_messageInfo_ReturnCode.Size(m)
}
func (m *ReturnCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnCode.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnCode proto.InternalMessageInfo

func (m *ReturnCode) GetCode() CodeType {
	if m != nil {
		return m.Code
	}
	return CodeType_OK
}

func (m *ReturnCode) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("mizar.CodeType", CodeType_name, CodeType_value)
	proto.RegisterType((*BuiltinsNodeMessage)(nil), "mizar.BuiltinsNodeMessage")
	proto.RegisterType((*BuiltinsPodMessage)(nil), "mizar.BuiltinsPodMessage")
	proto.RegisterType((*BuiltinsServiceMessage)(nil), "mizar.BuiltinsServiceMessage")
	proto.RegisterType((*BuiltinsServiceEndpointMessage)(nil), "mizar.BuiltinsServiceEndpointMessage")
	proto.RegisterType((*BuiltinsArktosMessage)(nil), "mizar.BuiltinsArktosMessage")
	proto.RegisterType((*BuiltinsNetworkPolicyMessage)(nil), "mizar.BuiltinsNetworkPolicyMessage")
	proto.RegisterType((*BuiltinsNamespaceMessage)(nil), "mizar.BuiltinsNamespaceMessage")
	proto.RegisterType((*PortsMessage)(nil), "mizar.PortsMessage")
	proto.RegisterType((*InterfacesMessage)(nil), "mizar.InterfacesMessage")
	proto.RegisterType((*ReturnCode)(nil), "mizar.ReturnCode")
}

func init() { proto.RegisterFile("builtins.proto", fileDescriptor_54ab063ef2b175be) }

var fileDescriptor_54ab063ef2b175be = []byte{
	// 794 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0x26, 0xce, 0x0f, 0x64, 0x20, 0x21, 0x2c, 0x07, 0x8e, 0x0f, 0x82, 0x03, 0xc7, 0x08, 0x29,
	0xa7, 0x17, 0x5c, 0xa4, 0x37, 0xad, 0x2a, 0x2e, 0x28, 0x8d, 0x5a, 0x8a, 0x20, 0x91, 0xa1, 0xb7,
	0x8d, 0x1c, 0x7b, 0x29, 0x2e, 0x89, 0xd7, 0xf2, 0x3a, 0x54, 0xf4, 0xaa, 0xaf, 0xd1, 0xb7, 0xe8,
	0x23, 0xf4, 0xcd, 0x5a, 0xed, 0xce, 0xda, 0x89, 0x4d, 0x1c, 0x55, 0x4e, 0xee, 0x32, 0x33, 0x3b,
	0xdf, 0xcc, 0x7c, 0x5f, 0x76, 0xc7, 0x50, 0xef, 0x8f, 0xdc, 0x41, 0xe8, 0x7a, 0xfc, 0xd8, 0x0f,
	0x58, 0xc8, 0x48, 0x79, 0xe8, 0x7e, 0xb5, 0x02, 0xe3, 0x25, 0x6c, 0xbe, 0x56, 0x81, 0x2b, 0xe6,
	0xd0, 0x4b, 0xca, 0xb9, 0xf5, 0x89, 0x12, 0x02, 0x25, 0xcf, 0x1a, 0x52, 0xbd, 0x70, 0x50, 0x68,
	0x56, 0x4d, 0xf9, 0x9b, 0xd4, 0x41, 0x73, 0x7d, 0x5d, 0x93, 0x1e, 0xcd, 0xf5, 0x8d, 0x1f, 0x1a,
	0x90, 0x28, 0xb7, 0xcb, 0x9c, 0x59, 0xa9, 0x7f, 0xc3, 0xf2, 0x1d, 0xe3, 0x61, 0x2f, 0xce, 0xaf,
	0x08, 0xf3, 0xdc, 0x27, 0xbb, 0x50, 0x15, 0x07, 0xb8, 0x6f, 0xd9, 0x54, 0x2f, 0xca, 0xd0, 0xd8,
	0x41, 0xb6, 0xa1, 0x12, 0x52, 0xcf, 0xf2, 0x42, 0xbd, 0x84, 0x59, 0x68, 0x09, 0xff, 0xc0, 0xea,
	0xd3, 0x01, 0xd7, 0xcb, 0xe8, 0x47, 0x8b, 0x1c, 0x41, 0xdd, 0x0a, 0xee, 0x43, 0xc6, 0x7b, 0x1e,
	0x0d, 0xbf, 0xb0, 0xe0, 0x5e, 0xaf, 0xc8, 0x78, 0x0d, 0xbd, 0x57, 0xe8, 0x24, 0x7f, 0x41, 0xd9,
	0xbf, 0xb3, 0x38, 0xd5, 0x97, 0x65, 0x14, 0x0d, 0xf2, 0x02, 0xc0, 0xf5, 0x42, 0x1a, 0xdc, 0x5a,
	0x36, 0xe5, 0xfa, 0xca, 0x41, 0xb1, 0xb9, 0xda, 0xd2, 0x8f, 0x25, 0x4b, 0xc7, 0xe7, 0x71, 0x40,
	0x4d, 0x69, 0x4e, 0x9c, 0x25, 0x0d, 0x28, 0x3e, 0xf8, 0xb6, 0x5e, 0x95, 0x68, 0xe2, 0xa7, 0x68,
	0x90, 0x8f, 0xfa, 0x1e, 0x0d, 0x75, 0xc0, 0x06, 0xd1, 0x32, 0xbe, 0x17, 0x60, 0x3b, 0xa2, 0xec,
	0x9a, 0x06, 0x0f, 0xae, 0x3d, 0x93, 0xf1, 0xa7, 0xf3, 0x68, 0xd3, 0xe6, 0xc9, 0x47, 0x22, 0xca,
	0x59, 0x8e, 0xe5, 0xfc, 0x55, 0x80, 0x7f, 0x53, 0xbd, 0xb5, 0x3d, 0xc7, 0x67, 0xae, 0x17, 0xce,
	0xea, 0x31, 0x51, 0x5c, 0xcb, 0x2e, 0x5e, 0x4c, 0x14, 0xdf, 0x87, 0xd5, 0xbe, 0x65, 0xdf, 0x53,
	0xcf, 0xe9, 0xb9, 0x3e, 0xd7, 0x4b, 0x07, 0xc5, 0x66, 0xd5, 0x04, 0xe5, 0x3a, 0xf7, 0x39, 0xf9,
	0x1f, 0xca, 0x3e, 0x0b, 0x42, 0xa1, 0xb0, 0x10, 0x62, 0x53, 0x09, 0xd1, 0x15, 0xbe, 0x48, 0x03,
	0x3c, 0x41, 0x9a, 0xd0, 0x98, 0xc0, 0xea, 0x7d, 0xe6, 0xcc, 0x53, 0xba, 0xd7, 0xc7, 0x80, 0xef,
	0x39, 0xf3, 0xc8, 0x1e, 0x80, 0x4c, 0xc1, 0x33, 0xa8, 0x7e, 0x55, 0x7a, 0x44, 0xd8, 0x38, 0x81,
	0xad, 0x88, 0x80, 0x53, 0x49, 0xf0, 0xac, 0xb9, 0x95, 0xe8, 0x5a, 0x2c, 0xba, 0xf1, 0xad, 0x00,
	0xbb, 0xf1, 0x5d, 0x42, 0x69, 0xba, 0x6c, 0xe0, 0xda, 0x8f, 0x8b, 0xa7, 0x6f, 0x1b, 0x2a, 0xbe,
	0x84, 0x8e, 0x34, 0x45, 0xcb, 0xf8, 0x08, 0x7a, 0xdc, 0x41, 0x04, 0x32, 0xab, 0xfa, 0x18, 0x5f,
	0xcb, 0xb8, 0x60, 0xc5, 0xc9, 0x0b, 0x66, 0x04, 0xb0, 0x36, 0xa9, 0x00, 0x39, 0x84, 0xda, 0x6d,
	0xc0, 0xbc, 0x50, 0x70, 0x2f, 0x78, 0x54, 0xe0, 0x6b, 0x91, 0x53, 0x1c, 0x26, 0xff, 0xc1, 0x5a,
	0xa4, 0x8f, 0x3c, 0x83, 0xa5, 0x22, 0xfd, 0xe5, 0x91, 0x1d, 0x58, 0x91, 0xaf, 0x92, 0xcd, 0x06,
	0xaa, 0x62, 0x6c, 0x1b, 0x1d, 0xd8, 0x78, 0x72, 0xfd, 0xfe, 0xe4, 0x7d, 0x9a, 0xb8, 0x84, 0xc5,
	0xc4, 0x25, 0xbc, 0x00, 0x30, 0x69, 0x38, 0x0a, 0xbc, 0x33, 0xe6, 0x88, 0x11, 0x4a, 0x36, 0x73,
	0x10, 0xa9, 0xde, 0x5a, 0x57, 0xff, 0x33, 0x11, 0xba, 0x79, 0xf4, 0xa9, 0x29, 0x83, 0x44, 0x87,
	0xe5, 0x21, 0x56, 0x56, 0xf8, 0x91, 0xf9, 0xac, 0x05, 0x2b, 0xd1, 0x59, 0x52, 0x01, 0xad, 0x73,
	0xd1, 0x58, 0x22, 0x75, 0x80, 0x9b, 0xf6, 0x65, 0xb7, 0xd7, 0x36, 0xcd, 0x8e, 0xd9, 0x28, 0x08,
	0xbb, 0xdb, 0x36, 0x2f, 0x95, 0xad, 0xb5, 0x7e, 0xd6, 0x60, 0x3d, 0x75, 0xd3, 0xc8, 0x19, 0xd4,
	0xce, 0x02, 0x6a, 0x85, 0x34, 0x72, 0xec, 0xa9, 0x4e, 0xa6, 0x3f, 0x17, 0x3b, 0x1b, 0x2a, 0x3c,
	0x9e, 0xc4, 0x58, 0x12, 0x20, 0x1f, 0x7c, 0x67, 0x7e, 0x10, 0x93, 0xf2, 0xd1, 0x70, 0x5e, 0x90,
	0x37, 0x74, 0x40, 0xe7, 0xeb, 0xe4, 0x1a, 0xb6, 0x12, 0xe3, 0x44, 0xcf, 0x11, 0x39, 0x9a, 0x0e,
	0x96, 0x7a, 0xae, 0x32, 0x41, 0x13, 0xe3, 0x2d, 0x0a, 0x34, 0xa1, 0xde, 0x42, 0x40, 0x5f, 0x41,
	0x15, 0x3b, 0xed, 0x32, 0x87, 0xfc, 0x93, 0x02, 0x1a, 0x2f, 0xdc, 0xcc, 0x64, 0xe4, 0x2e, 0x67,
	0x32, 0x8e, 0x93, 0x33, 0x19, 0xa5, 0xcf, 0x93, 0x7c, 0x02, 0x80, 0x95, 0xc5, 0xc7, 0x08, 0xd9,
	0x49, 0x65, 0x4f, 0x7c, 0xa1, 0x64, 0xa6, 0x23, 0x65, 0xb9, 0xd3, 0x91, 0xb4, 0xdc, 0xe9, 0x38,
	0x79, 0xbe, 0xf4, 0x77, 0xb0, 0x89, 0xb3, 0x9f, 0x26, 0xb7, 0x7b, 0x0a, 0x27, 0xb1, 0x9a, 0x32,
	0x91, 0x90, 0x86, 0x45, 0x20, 0x21, 0x23, 0x73, 0x23, 0x75, 0x22, 0xa4, 0xc4, 0x6a, 0x24, 0x87,
	0x69, 0x96, 0xa6, 0x2c, 0xce, 0x4c, 0x40, 0xf5, 0x57, 0x59, 0x1c, 0xa0, 0x92, 0x6f, 0x41, 0x80,
	0x6f, 0x61, 0x5d, 0x8d, 0x1c, 0x2f, 0xf4, 0xfd, 0x34, 0x58, 0x6a, 0x4b, 0x67, 0x02, 0xa9, 0x51,
	0xe7, 0x07, 0x52, 0x23, 0xce, 0x07, 0xd4, 0xaf, 0xc8, 0xf5, 0xfc, 0xfc, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x9b, 0x4f, 0x1c, 0x41, 0x56, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BuiltinsServiceClient is the client API for BuiltinsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuiltinsServiceClient interface {
	// For Services/Service Endpoints, network controller may want to annotate the Endpoints.
	// If Endpoints are not annotated, there will be many updates from unwanted endpoints.
	CreateService(ctx context.Context, in *BuiltinsServiceMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	UpdateService(ctx context.Context, in *BuiltinsServiceMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	ResumeService(ctx context.Context, in *BuiltinsServiceMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	DeleteService(ctx context.Context, in *BuiltinsServiceMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	UpdateServiceEndpoint(ctx context.Context, in *BuiltinsServiceEndpointMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	ResumeServiceEndpoint(ctx context.Context, in *BuiltinsServiceEndpointMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	CreateServiceEndpoint(ctx context.Context, in *BuiltinsServiceEndpointMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	ResumePod(ctx context.Context, in *BuiltinsPodMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	UpdatePod(ctx context.Context, in *BuiltinsPodMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	CreatePod(ctx context.Context, in *BuiltinsPodMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	DeletePod(ctx context.Context, in *BuiltinsPodMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	CreateNode(ctx context.Context, in *BuiltinsNodeMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	ResumeNode(ctx context.Context, in *BuiltinsNodeMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	UpdateNode(ctx context.Context, in *BuiltinsNodeMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	DeleteNode(ctx context.Context, in *BuiltinsNodeMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	CreateArktosNetwork(ctx context.Context, in *BuiltinsArktosMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	ResumeArktosNetwork(ctx context.Context, in *BuiltinsArktosMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	UpdateArktosNetwork(ctx context.Context, in *BuiltinsArktosMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	UpdateNetworkPolicy(ctx context.Context, in *BuiltinsNetworkPolicyMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	CreateNetworkPolicy(ctx context.Context, in *BuiltinsNetworkPolicyMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	DeleteNetworkPolicy(ctx context.Context, in *BuiltinsNetworkPolicyMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	UpdateNamespace(ctx context.Context, in *BuiltinsNamespaceMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	CreateNamespace(ctx context.Context, in *BuiltinsNamespaceMessage, opts ...grpc.CallOption) (*ReturnCode, error)
	DeleteNamespace(ctx context.Context, in *BuiltinsNamespaceMessage, opts ...grpc.CallOption) (*ReturnCode, error)
}

type builtinsServiceClient struct {
	cc *grpc.ClientConn
}

func NewBuiltinsServiceClient(cc *grpc.ClientConn) BuiltinsServiceClient {
	return &builtinsServiceClient{cc}
}

func (c *builtinsServiceClient) CreateService(ctx context.Context, in *BuiltinsServiceMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/CreateService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) UpdateService(ctx context.Context, in *BuiltinsServiceMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/UpdateService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) ResumeService(ctx context.Context, in *BuiltinsServiceMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/ResumeService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) DeleteService(ctx context.Context, in *BuiltinsServiceMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/DeleteService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) UpdateServiceEndpoint(ctx context.Context, in *BuiltinsServiceEndpointMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/UpdateServiceEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) ResumeServiceEndpoint(ctx context.Context, in *BuiltinsServiceEndpointMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/ResumeServiceEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) CreateServiceEndpoint(ctx context.Context, in *BuiltinsServiceEndpointMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/CreateServiceEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) ResumePod(ctx context.Context, in *BuiltinsPodMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/ResumePod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) UpdatePod(ctx context.Context, in *BuiltinsPodMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/UpdatePod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) CreatePod(ctx context.Context, in *BuiltinsPodMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/CreatePod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) DeletePod(ctx context.Context, in *BuiltinsPodMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/DeletePod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) CreateNode(ctx context.Context, in *BuiltinsNodeMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/CreateNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) ResumeNode(ctx context.Context, in *BuiltinsNodeMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/ResumeNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) UpdateNode(ctx context.Context, in *BuiltinsNodeMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/UpdateNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) DeleteNode(ctx context.Context, in *BuiltinsNodeMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/DeleteNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) CreateArktosNetwork(ctx context.Context, in *BuiltinsArktosMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/CreateArktosNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) ResumeArktosNetwork(ctx context.Context, in *BuiltinsArktosMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/ResumeArktosNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) UpdateArktosNetwork(ctx context.Context, in *BuiltinsArktosMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/UpdateArktosNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) UpdateNetworkPolicy(ctx context.Context, in *BuiltinsNetworkPolicyMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/UpdateNetworkPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) CreateNetworkPolicy(ctx context.Context, in *BuiltinsNetworkPolicyMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/CreateNetworkPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) DeleteNetworkPolicy(ctx context.Context, in *BuiltinsNetworkPolicyMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/DeleteNetworkPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) UpdateNamespace(ctx context.Context, in *BuiltinsNamespaceMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/UpdateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) CreateNamespace(ctx context.Context, in *BuiltinsNamespaceMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/CreateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builtinsServiceClient) DeleteNamespace(ctx context.Context, in *BuiltinsNamespaceMessage, opts ...grpc.CallOption) (*ReturnCode, error) {
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, "/mizar.BuiltinsService/DeleteNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuiltinsServiceServer is the server API for BuiltinsService service.
type BuiltinsServiceServer interface {
	// For Services/Service Endpoints, network controller may want to annotate the Endpoints.
	// If Endpoints are not annotated, there will be many updates from unwanted endpoints.
	CreateService(context.Context, *BuiltinsServiceMessage) (*ReturnCode, error)
	UpdateService(context.Context, *BuiltinsServiceMessage) (*ReturnCode, error)
	ResumeService(context.Context, *BuiltinsServiceMessage) (*ReturnCode, error)
	DeleteService(context.Context, *BuiltinsServiceMessage) (*ReturnCode, error)
	UpdateServiceEndpoint(context.Context, *BuiltinsServiceEndpointMessage) (*ReturnCode, error)
	ResumeServiceEndpoint(context.Context, *BuiltinsServiceEndpointMessage) (*ReturnCode, error)
	CreateServiceEndpoint(context.Context, *BuiltinsServiceEndpointMessage) (*ReturnCode, error)
	ResumePod(context.Context, *BuiltinsPodMessage) (*ReturnCode, error)
	UpdatePod(context.Context, *BuiltinsPodMessage) (*ReturnCode, error)
	CreatePod(context.Context, *BuiltinsPodMessage) (*ReturnCode, error)
	DeletePod(context.Context, *BuiltinsPodMessage) (*ReturnCode, error)
	CreateNode(context.Context, *BuiltinsNodeMessage) (*ReturnCode, error)
	ResumeNode(context.Context, *BuiltinsNodeMessage) (*ReturnCode, error)
	UpdateNode(context.Context, *BuiltinsNodeMessage) (*ReturnCode, error)
	DeleteNode(context.Context, *BuiltinsNodeMessage) (*ReturnCode, error)
	CreateArktosNetwork(context.Context, *BuiltinsArktosMessage) (*ReturnCode, error)
	ResumeArktosNetwork(context.Context, *BuiltinsArktosMessage) (*ReturnCode, error)
	UpdateArktosNetwork(context.Context, *BuiltinsArktosMessage) (*ReturnCode, error)
	UpdateNetworkPolicy(context.Context, *BuiltinsNetworkPolicyMessage) (*ReturnCode, error)
	CreateNetworkPolicy(context.Context, *BuiltinsNetworkPolicyMessage) (*ReturnCode, error)
	DeleteNetworkPolicy(context.Context, *BuiltinsNetworkPolicyMessage) (*ReturnCode, error)
	UpdateNamespace(context.Context, *BuiltinsNamespaceMessage) (*ReturnCode, error)
	CreateNamespace(context.Context, *BuiltinsNamespaceMessage) (*ReturnCode, error)
	DeleteNamespace(context.Context, *BuiltinsNamespaceMessage) (*ReturnCode, error)
}

// UnimplementedBuiltinsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBuiltinsServiceServer struct {
}

func (*UnimplementedBuiltinsServiceServer) CreateService(ctx context.Context, req *BuiltinsServiceMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateService not implemented")
}
func (*UnimplementedBuiltinsServiceServer) UpdateService(ctx context.Context, req *BuiltinsServiceMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateService not implemented")
}
func (*UnimplementedBuiltinsServiceServer) ResumeService(ctx context.Context, req *BuiltinsServiceMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeService not implemented")
}
func (*UnimplementedBuiltinsServiceServer) DeleteService(ctx context.Context, req *BuiltinsServiceMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteService not implemented")
}
func (*UnimplementedBuiltinsServiceServer) UpdateServiceEndpoint(ctx context.Context, req *BuiltinsServiceEndpointMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServiceEndpoint not implemented")
}
func (*UnimplementedBuiltinsServiceServer) ResumeServiceEndpoint(ctx context.Context, req *BuiltinsServiceEndpointMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeServiceEndpoint not implemented")
}
func (*UnimplementedBuiltinsServiceServer) CreateServiceEndpoint(ctx context.Context, req *BuiltinsServiceEndpointMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServiceEndpoint not implemented")
}
func (*UnimplementedBuiltinsServiceServer) ResumePod(ctx context.Context, req *BuiltinsPodMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumePod not implemented")
}
func (*UnimplementedBuiltinsServiceServer) UpdatePod(ctx context.Context, req *BuiltinsPodMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePod not implemented")
}
func (*UnimplementedBuiltinsServiceServer) CreatePod(ctx context.Context, req *BuiltinsPodMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePod not implemented")
}
func (*UnimplementedBuiltinsServiceServer) DeletePod(ctx context.Context, req *BuiltinsPodMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePod not implemented")
}
func (*UnimplementedBuiltinsServiceServer) CreateNode(ctx context.Context, req *BuiltinsNodeMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNode not implemented")
}
func (*UnimplementedBuiltinsServiceServer) ResumeNode(ctx context.Context, req *BuiltinsNodeMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeNode not implemented")
}
func (*UnimplementedBuiltinsServiceServer) UpdateNode(ctx context.Context, req *BuiltinsNodeMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNode not implemented")
}
func (*UnimplementedBuiltinsServiceServer) DeleteNode(ctx context.Context, req *BuiltinsNodeMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNode not implemented")
}
func (*UnimplementedBuiltinsServiceServer) CreateArktosNetwork(ctx context.Context, req *BuiltinsArktosMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArktosNetwork not implemented")
}
func (*UnimplementedBuiltinsServiceServer) ResumeArktosNetwork(ctx context.Context, req *BuiltinsArktosMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeArktosNetwork not implemented")
}
func (*UnimplementedBuiltinsServiceServer) UpdateArktosNetwork(ctx context.Context, req *BuiltinsArktosMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateArktosNetwork not implemented")
}
func (*UnimplementedBuiltinsServiceServer) UpdateNetworkPolicy(ctx context.Context, req *BuiltinsNetworkPolicyMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNetworkPolicy not implemented")
}
func (*UnimplementedBuiltinsServiceServer) CreateNetworkPolicy(ctx context.Context, req *BuiltinsNetworkPolicyMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNetworkPolicy not implemented")
}
func (*UnimplementedBuiltinsServiceServer) DeleteNetworkPolicy(ctx context.Context, req *BuiltinsNetworkPolicyMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNetworkPolicy not implemented")
}
func (*UnimplementedBuiltinsServiceServer) UpdateNamespace(ctx context.Context, req *BuiltinsNamespaceMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNamespace not implemented")
}
func (*UnimplementedBuiltinsServiceServer) CreateNamespace(ctx context.Context, req *BuiltinsNamespaceMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (*UnimplementedBuiltinsServiceServer) DeleteNamespace(ctx context.Context, req *BuiltinsNamespaceMessage) (*ReturnCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNamespace not implemented")
}

func RegisterBuiltinsServiceServer(s *grpc.Server, srv BuiltinsServiceServer) {
	s.RegisterService(&_BuiltinsService_serviceDesc, srv)
}

func _BuiltinsService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsServiceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/CreateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).CreateService(ctx, req.(*BuiltinsServiceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsServiceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/UpdateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).UpdateService(ctx, req.(*BuiltinsServiceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_ResumeService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsServiceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).ResumeService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/ResumeService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).ResumeService(ctx, req.(*BuiltinsServiceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsServiceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/DeleteService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).DeleteService(ctx, req.(*BuiltinsServiceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_UpdateServiceEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsServiceEndpointMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).UpdateServiceEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/UpdateServiceEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).UpdateServiceEndpoint(ctx, req.(*BuiltinsServiceEndpointMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_ResumeServiceEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsServiceEndpointMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).ResumeServiceEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/ResumeServiceEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).ResumeServiceEndpoint(ctx, req.(*BuiltinsServiceEndpointMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_CreateServiceEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsServiceEndpointMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).CreateServiceEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/CreateServiceEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).CreateServiceEndpoint(ctx, req.(*BuiltinsServiceEndpointMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_ResumePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsPodMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).ResumePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/ResumePod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).ResumePod(ctx, req.(*BuiltinsPodMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_UpdatePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsPodMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).UpdatePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/UpdatePod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).UpdatePod(ctx, req.(*BuiltinsPodMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_CreatePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsPodMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).CreatePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/CreatePod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).CreatePod(ctx, req.(*BuiltinsPodMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_DeletePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsPodMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).DeletePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/DeletePod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).DeletePod(ctx, req.(*BuiltinsPodMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsNodeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/CreateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).CreateNode(ctx, req.(*BuiltinsNodeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_ResumeNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsNodeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).ResumeNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/ResumeNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).ResumeNode(ctx, req.(*BuiltinsNodeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsNodeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/UpdateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).UpdateNode(ctx, req.(*BuiltinsNodeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsNodeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/DeleteNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).DeleteNode(ctx, req.(*BuiltinsNodeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_CreateArktosNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsArktosMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).CreateArktosNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/CreateArktosNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).CreateArktosNetwork(ctx, req.(*BuiltinsArktosMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_ResumeArktosNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsArktosMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).ResumeArktosNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/ResumeArktosNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).ResumeArktosNetwork(ctx, req.(*BuiltinsArktosMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_UpdateArktosNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsArktosMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).UpdateArktosNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/UpdateArktosNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).UpdateArktosNetwork(ctx, req.(*BuiltinsArktosMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_UpdateNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsNetworkPolicyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).UpdateNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/UpdateNetworkPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).UpdateNetworkPolicy(ctx, req.(*BuiltinsNetworkPolicyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_CreateNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsNetworkPolicyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).CreateNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/CreateNetworkPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).CreateNetworkPolicy(ctx, req.(*BuiltinsNetworkPolicyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_DeleteNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsNetworkPolicyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).DeleteNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/DeleteNetworkPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).DeleteNetworkPolicy(ctx, req.(*BuiltinsNetworkPolicyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_UpdateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsNamespaceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).UpdateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/UpdateNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).UpdateNamespace(ctx, req.(*BuiltinsNamespaceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsNamespaceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/CreateNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).CreateNamespace(ctx, req.(*BuiltinsNamespaceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuiltinsService_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinsNamespaceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuiltinsServiceServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mizar.BuiltinsService/DeleteNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuiltinsServiceServer).DeleteNamespace(ctx, req.(*BuiltinsNamespaceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _BuiltinsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mizar.BuiltinsService",
	HandlerType: (*BuiltinsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateService",
			Handler:    _BuiltinsService_CreateService_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _BuiltinsService_UpdateService_Handler,
		},
		{
			MethodName: "ResumeService",
			Handler:    _BuiltinsService_ResumeService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _BuiltinsService_DeleteService_Handler,
		},
		{
			MethodName: "UpdateServiceEndpoint",
			Handler:    _BuiltinsService_UpdateServiceEndpoint_Handler,
		},
		{
			MethodName: "ResumeServiceEndpoint",
			Handler:    _BuiltinsService_ResumeServiceEndpoint_Handler,
		},
		{
			MethodName: "CreateServiceEndpoint",
			Handler:    _BuiltinsService_CreateServiceEndpoint_Handler,
		},
		{
			MethodName: "ResumePod",
			Handler:    _BuiltinsService_ResumePod_Handler,
		},
		{
			MethodName: "UpdatePod",
			Handler:    _BuiltinsService_UpdatePod_Handler,
		},
		{
			MethodName: "CreatePod",
			Handler:    _BuiltinsService_CreatePod_Handler,
		},
		{
			MethodName: "DeletePod",
			Handler:    _BuiltinsService_DeletePod_Handler,
		},
		{
			MethodName: "CreateNode",
			Handler:    _BuiltinsService_CreateNode_Handler,
		},
		{
			MethodName: "ResumeNode",
			Handler:    _BuiltinsService_ResumeNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _BuiltinsService_UpdateNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _BuiltinsService_DeleteNode_Handler,
		},
		{
			MethodName: "CreateArktosNetwork",
			Handler:    _BuiltinsService_CreateArktosNetwork_Handler,
		},
		{
			MethodName: "ResumeArktosNetwork",
			Handler:    _BuiltinsService_ResumeArktosNetwork_Handler,
		},
		{
			MethodName: "UpdateArktosNetwork",
			Handler:    _BuiltinsService_UpdateArktosNetwork_Handler,
		},
		{
			MethodName: "UpdateNetworkPolicy",
			Handler:    _BuiltinsService_UpdateNetworkPolicy_Handler,
		},
		{
			MethodName: "CreateNetworkPolicy",
			Handler:    _BuiltinsService_CreateNetworkPolicy_Handler,
		},
		{
			MethodName: "DeleteNetworkPolicy",
			Handler:    _BuiltinsService_DeleteNetworkPolicy_Handler,
		},
		{
			MethodName: "UpdateNamespace",
			Handler:    _BuiltinsService_UpdateNamespace_Handler,
		},
		{
			MethodName: "CreateNamespace",
			Handler:    _BuiltinsService_CreateNamespace_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _BuiltinsService_DeleteNamespace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "builtins.proto",
}
