/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	cloudgatewayv1 "k8s.io/kubernetes/pkg/apis/cloudgateway/v1"
)

// FakeESites implements ESiteInterface
type FakeESites struct {
	Fake *FakeCloudgatewayV1
	ns   string
	te   string
}

var esitesResource = schema.GroupVersionResource{Group: "cloudgateway.arktos.io", Version: "v1", Resource: "esites"}

var esitesKind = schema.GroupVersionKind{Group: "cloudgateway.arktos.io", Version: "v1", Kind: "ESite"}

// Get takes name of the eSite, and returns the corresponding eSite object, and an error if there is any.
func (c *FakeESites) Get(name string, options v1.GetOptions) (result *cloudgatewayv1.ESite, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithMultiTenancy(esitesResource, c.ns, name, c.te), &cloudgatewayv1.ESite{})

	if obj == nil {
		return nil, err
	}

	return obj.(*cloudgatewayv1.ESite), err
}

// List takes label and field selectors, and returns the list of ESites that match those selectors.
func (c *FakeESites) List(opts v1.ListOptions) (result *cloudgatewayv1.ESiteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithMultiTenancy(esitesResource, esitesKind, c.ns, opts, c.te), &cloudgatewayv1.ESiteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cloudgatewayv1.ESiteList{ListMeta: obj.(*cloudgatewayv1.ESiteList).ListMeta}
	for _, item := range obj.(*cloudgatewayv1.ESiteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.AggregatedWatchInterface that watches the requested eSites.
func (c *FakeESites) Watch(opts v1.ListOptions) watch.AggregatedWatchInterface {
	aggWatch := watch.NewAggregatedWatcher()
	watcher, err := c.Fake.
		InvokesWatch(testing.NewWatchActionWithMultiTenancy(esitesResource, c.ns, opts, c.te))

	aggWatch.AddWatchInterface(watcher, err)
	return aggWatch
}

// Create takes the representation of a eSite and creates it.  Returns the server's representation of the eSite, and an error, if there is any.
func (c *FakeESites) Create(eSite *cloudgatewayv1.ESite) (result *cloudgatewayv1.ESite, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithMultiTenancy(esitesResource, c.ns, eSite, c.te), &cloudgatewayv1.ESite{})

	if obj == nil {
		return nil, err
	}

	return obj.(*cloudgatewayv1.ESite), err
}

// Update takes the representation of a eSite and updates it. Returns the server's representation of the eSite, and an error, if there is any.
func (c *FakeESites) Update(eSite *cloudgatewayv1.ESite) (result *cloudgatewayv1.ESite, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithMultiTenancy(esitesResource, c.ns, eSite, c.te), &cloudgatewayv1.ESite{})

	if obj == nil {
		return nil, err
	}

	return obj.(*cloudgatewayv1.ESite), err
}

// Delete takes name of the eSite and deletes it. Returns an error if one occurs.
func (c *FakeESites) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithMultiTenancy(esitesResource, c.ns, name, c.te), &cloudgatewayv1.ESite{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeESites) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithMultiTenancy(esitesResource, c.ns, listOptions, c.te)

	_, err := c.Fake.Invokes(action, &cloudgatewayv1.ESiteList{})
	return err
}

// Patch applies the patch and returns the patched eSite.
func (c *FakeESites) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *cloudgatewayv1.ESite, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithMultiTenancy(esitesResource, c.te, c.ns, name, pt, data, subresources...), &cloudgatewayv1.ESite{})

	if obj == nil {
		return nil, err
	}

	return obj.(*cloudgatewayv1.ESite), err
}
