/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	cloudgatewayv1 "k8s.io/kubernetes/pkg/apis/cloudgateway/v1"
)

// FakeEServers implements EServerInterface
type FakeEServers struct {
	Fake *FakeCloudgatewayV1
	ns   string
	te   string
}

var eserversResource = schema.GroupVersionResource{Group: "cloudgateway.arktos.io", Version: "v1", Resource: "eservers"}

var eserversKind = schema.GroupVersionKind{Group: "cloudgateway.arktos.io", Version: "v1", Kind: "EServer"}

// Get takes name of the eServer, and returns the corresponding eServer object, and an error if there is any.
func (c *FakeEServers) Get(name string, options v1.GetOptions) (result *cloudgatewayv1.EServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithMultiTenancy(eserversResource, c.ns, name, c.te), &cloudgatewayv1.EServer{})

	if obj == nil {
		return nil, err
	}

	return obj.(*cloudgatewayv1.EServer), err
}

// List takes label and field selectors, and returns the list of EServers that match those selectors.
func (c *FakeEServers) List(opts v1.ListOptions) (result *cloudgatewayv1.EServerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithMultiTenancy(eserversResource, eserversKind, c.ns, opts, c.te), &cloudgatewayv1.EServerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cloudgatewayv1.EServerList{ListMeta: obj.(*cloudgatewayv1.EServerList).ListMeta}
	for _, item := range obj.(*cloudgatewayv1.EServerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.AggregatedWatchInterface that watches the requested eServers.
func (c *FakeEServers) Watch(opts v1.ListOptions) watch.AggregatedWatchInterface {
	aggWatch := watch.NewAggregatedWatcher()
	watcher, err := c.Fake.
		InvokesWatch(testing.NewWatchActionWithMultiTenancy(eserversResource, c.ns, opts, c.te))

	aggWatch.AddWatchInterface(watcher, err)
	return aggWatch
}

// Create takes the representation of a eServer and creates it.  Returns the server's representation of the eServer, and an error, if there is any.
func (c *FakeEServers) Create(eServer *cloudgatewayv1.EServer) (result *cloudgatewayv1.EServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithMultiTenancy(eserversResource, c.ns, eServer, c.te), &cloudgatewayv1.EServer{})

	if obj == nil {
		return nil, err
	}

	return obj.(*cloudgatewayv1.EServer), err
}

// Update takes the representation of a eServer and updates it. Returns the server's representation of the eServer, and an error, if there is any.
func (c *FakeEServers) Update(eServer *cloudgatewayv1.EServer) (result *cloudgatewayv1.EServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithMultiTenancy(eserversResource, c.ns, eServer, c.te), &cloudgatewayv1.EServer{})

	if obj == nil {
		return nil, err
	}

	return obj.(*cloudgatewayv1.EServer), err
}

// Delete takes name of the eServer and deletes it. Returns an error if one occurs.
func (c *FakeEServers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithMultiTenancy(eserversResource, c.ns, name, c.te), &cloudgatewayv1.EServer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEServers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithMultiTenancy(eserversResource, c.ns, listOptions, c.te)

	_, err := c.Fake.Invokes(action, &cloudgatewayv1.EServerList{})
	return err
}

// Patch applies the patch and returns the patched eServer.
func (c *FakeEServers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *cloudgatewayv1.EServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithMultiTenancy(eserversResource, c.te, c.ns, name, pt, data, subresources...), &cloudgatewayv1.EServer{})

	if obj == nil {
		return nil, err
	}

	return obj.(*cloudgatewayv1.EServer), err
}
