apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networks.arktos.futurewei.com
  labels:
    arktos.futurewei.com/crd-sharing-policy: forced
spec:
  group: arktos.futurewei.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Tenant
  subresources:
    status: {}
  names:
    plural: networks
    singular: network
    kind: Network
    shortNames:
    - ne
    - net
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            type:
              type: string
            vpcID:
              type: string
            service:
              type: object
              properties:
                ipam:
                  type: string
                  enum: ["Arktos", "Kubernetes", "External"]
                cidrs:
                  type: array
                  items:
                    type: string
                    pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))$'
        status:
          type: object
          properties:
            phase:
              type: string
              enum: [Pending, Ready, Failed, Unknown, Terminating]
            message:
              type: string
            dnsServiceIP:
              type: string
  additionalPrinterColumns:
  - name: Type
    type: string
    JSONPath: .spec.type
  - name:  VPC
    type: string
    JSONPath: .spec.vpcID
  - name: Phase
    type: string
    JSONPath: .status.phase
  - name: DNS
    type: string
    JSONPath: .status.dnsServiceIP
